/**
 * Realistic patient profiles derived from the Medical Check-up dataset
 * for 1-click testing in the web demo.
 */
export const SAMPLE_PATIENTS = [
  {
    id: 'sample-sehat',
    name: 'Kasus 1: Sehat / Normal',
    description: 'Profil normal tanpa indikasi patologis signifikan',
    expectedClass: 'Sehat / Tidak Ada Indikasi',
    data: {
      JENIS_KELAMIN: 0, // Laki-laki
      UMUR_TAHUN: 28,
      'cholesterol total': 165.0,
      creatinin: 0.85,
      fbs: 88.0,
      rbs: 110.0,
      hgb: 14.5,
      'lymfosit%': 32.0,
      mch: 28.5,
      mchc: 33.5,
      mcv: 85.0,
      ureum: 26.0,
      wbc: 6.8,
    },
  },
  {
    id: 'sample-jantung',
    name: 'Kasus 2: Jantung & Kardiovaskular',
    description: 'Kolesterol tinggi dan usia lanjut dengan profil vaskular',
    expectedClass: 'Jantung dan Pembuluh Darah',
    data: {
      JENIS_KELAMIN: 1, // Perempuan
      UMUR_TAHUN: 64,
      'cholesterol total': 282.5,
      creatinin: 1.65,
      fbs: 122.0,
      rbs: 175.0,
      hgb: 12.0,
      'lymfosit%': 24.5,
      mch: 26.2,
      mchc: 32.0,
      mcv: 80.5,
      ureum: 52.0,
      wbc: 8.4,
    },
  },
  {
    id: 'sample-penyakit-dalam',
    name: 'Kasus 3: Penyakit Dalam / Metabolik',
    description: 'Gula darah tinggi (FBS/RBS) serta gangguan fungsi ginjal (Ureum & Kreatinin)',
    expectedClass: 'Spes. Penyakit Dalam',
    data: {
      JENIS_KELAMIN: 1,
      UMUR_TAHUN: 58,
      'cholesterol total': 228.0,
      creatinin: 3.45,
      fbs: 235.0,
      rbs: 310.0,
      hgb: 10.8,
      'lymfosit%': 21.0,
      mch: 25.5,
      mchc: 31.8,
      mcv: 78.0,
      ureum: 115.0,
      wbc: 9.6,
    },
  },
  {
    id: 'sample-paru',
    name: 'Kasus 4: Paru-Paru / Respiratorik',
    description: 'Leukositosis (WBC tinggi), limfosit abnormal, dan anemia ringan',
    expectedClass: 'Spes. Paru-Paru',
    data: {
      JENIS_KELAMIN: 0,
      UMUR_TAHUN: 52,
      'cholesterol total': 185.0,
      creatinin: 1.1,
      fbs: 95.0,
      rbs: 130.0,
      hgb: 9.8,
      'lymfosit%': 12.5,
      mch: 24.0,
      mchc: 30.5,
      mcv: 76.5,
      ureum: 44.0,
      wbc: 16.8,
    },
  },
];
